yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/templates/includes/footer.html
{% now "Y" as current_year %}

<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}


<header>
  <nav class="navbar navbar-expand-md sticky-top navbar-light" style="background-color: lightskyblue">
    <div class="container">
{#      <button aria-haspopup="true" aria-expanded="false">#}
{#        Сложность#}
{#        <span aria-hidden="true" >&#x25be;</span>#}
{#      </button>#}
      <button type="button"  data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle"
              aria-controls="navbarCollapse" aria-expanded="true">
        <span class="navbar-toggle-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <div id="navbarCollapse" class="collapse navbar-collapse navbar-right">
{#        {% with request.resolver_match.view_name as view_name %}#}
          <ul class="nav nav-pills ml-auto">
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
                href="{% url 'about:author' %}"
              >
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
                href="{% url 'about:tech' %}"
              >
                Технологии
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
                  href="{% url 'posts:post_create' %}"
                >
                  Новая запись
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name  == 'users:password_change' %}active{% endif %}"
                  href="{% url 'users:password_change' %}"
                >
                  Изменить пароль
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
                  href="{% url 'users:logout' %}"
                >
                  Выйти
                </a>
              </li>
              <li>
                Пользователь: {{ user.username }}
              <li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
                  href="{% url 'users:login' %}"
                >
                  Войти
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
                  href="{% url 'users:signup' %}"
                >
                  Регистрация
                </a>
              </li>
            {% endif %}
          </ul>
{#              <form action="" class="d-flex">#}
{#                <input type="search" placeholder="" class="form-control mr-auto ml-2">#}
{#                <button class="btn btn-outline-light">Поиск</button>#}
{#              </form>#}
        </div>
        {% endwith %}
{#      </div>#}
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/users_registration_templates.html
{% extends "base.html" %}
{% block title %}Загаловок{% endblock %}

{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% block card-header %} Заголовок {% endblock %}
      </div>
      <div class="card-body">
        {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
          <div>
            {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
          </div>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}