yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Имя', max_length=200, unique=True)
    slug = models.SlugField('Адрес', unique=True)
    description = models.TextField('Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group']

yatube/posts/views.py
from django.conf import settings
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .models import Group, Post, User
from .forms import PostForm


# Главная страница
def index(request):
    template = 'posts/index.html'
    # Сортировка постов по полю pub_date по убыванию.
    posts = Post.objects.all()
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_LIMIT)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context)


# Страница с постами сообщества.
def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    # Сортировка постов по полю pub_date по убыванию.
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:settings.PAGE_LIMIT]
    post_list = Post.objects.all()
    paginator = Paginator(post_list, settings.PAGE_LIMIT)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get('page')

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, template, context, slug)


def paginator(request, post_list):
    paginator = Paginator(post_list, settings.PAGE_LIMIT)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return page_obj


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.filter(author__exact=author)
    paginator = Paginator(post_list, settings.PAGE_LIMIT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'author': author,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    # Здесь код запроса к модели и создание словаря контекста
    post = get_object_or_404(Post, pk=post_id)
    page_number = request.GET.get('page' or None)
    context = {
        'post': post,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            Post.objects.create(
                text=text,
                group=group,
                author=request.user,
            )
            return redirect('posts:profile', request.user.username)
        return render(request, 'posts/post_create.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/post_create.html', {'form': form})

@login_required
def post_edit(request, post_id):
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, instance=post)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if request.method == 'POST':
        if form.is_valid():
            post.text = form.cleaned_data['text']
            post.group = form.cleaned_data['group']
            post.save()
            return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, 'posts/post_create.html', context)
    form = PostForm()
    return redirect('posts:post_detail', post_id)

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  <title>Записи сообщества {{ group.title }}</title>
{% endblock %}

{% block content %}
  <h2>Записи сообщества {{ group.title }}</h2>
  <p>
    {{ group.description }}
  </p>
  {% for post in posts %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  <title>Последние обновления на сайте</title>
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if post.group.slug %}
      все записи группы
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a>
    {% endif %}
    {% if not forloop.last %}<hr> {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
    {% if is_edit %}
      Редактировать запись
    {% else %}
      Добавить запись
    {% endif %}
{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if is_edit %}
          Редактировать запись
        {% else %}
          Добавить запись
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" >
          {% csrf_token %}
          <div class="form-group row my-3 p-3">
            <label for="id_text">
              Текст поста
              <span class="required text-danger" >*</span>
            </label>
            {{ form.text|addclass:'form-control' }}
            <small id="id_text-help" class="form-text text-muted">
              {% if is_edit %}
                Текст редактируемого поста
              {% else %}
                Текст нового поста
              {% endif %}
            </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="id_group">
              Группа
            </label>
            {{ form.group|addclass:'form-control' }}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>
          </div>
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{#{% extends "base.html" %}#}
{#{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}#}
{#{% block content %}#}
{#    <div class="row">#}
{#    <aside class="col-12 col-md-3">#}
{#      <ul class="list-group list-group-flush">#}
{#        <li class="list-group-item">#}
{#          Дата публикации: {{ post.pub_date|date:"d E Y" }} <!-- 31 июля 1854 -->#}
{#        </li>#}
{#        {% if post.group %}#}
{#          <li class="list-group-item">#}
{#            Группа: {{ post.group }}#}
{#            <a href="{% url 'posts:posts_list' post.group.slug %}">#}
{#              все записи группы#}
{#            </a>#}
{#          </li>#}
{#        {% endif %}#}
{#        <li class="list-group-item">#}
{#          Автор: {{post.author.get_full_name}}#}
{#        </li>#}
{#        <li class="list-group-item d-flex justify-content-between align-items-center">#}
{#          Всего постов автора:  <span >{{post.count}}</span>#}
{#        </li>#}
{#        <li class="list-group-item">#}
{#          <a href="{% url 'posts:profile' post.author %}">#}
{#            все посты пользователя#}
{#          </a>#}
{#        </li>#}
{#      </ul>#}
{#    </aside>#}
{#    <article class="col-12 col-md-9">#}
{#      <p>#}
{#       {{ post.text|linebreaksbr }}#}
{#      </p>#}
{#    </article>#}
{#  </div>#}
{#{% endblock %}#}

{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }} <!-- 31 июля 1854 -->
        </li>
        <!-- если у поста есть группа -->
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }} <!-- Название группы -->
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{  post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>{{ post.text|linebreaksbr }}</p>
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{#{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}#}
{#{% block content %}#}
{#  <div class="container py-5">#}
{#    <h1>Все посты пользователя {{ author.get_full_name }} </h1>#}
{#    <h3>Всего постов: {{ author.posts.count }} </h3>#}
{#    {% for post in page_obj %}#}
{#    <article>#}
{#      <ul>#}
{#        <li>#}
{#          Автор: {{ post.author.get_full_name }}#}
{#          <a href="{% url 'posts:profile' post.group.slug %}">все посты пользователя</a>#}
{#        </li>#}
{#        <li>#}
{#          Дата публикации: {{ post.pub_date|date:"d E Y" }}#}
{#        </li>#}
{#      </ul>#}
{#      <p>#}
{#      {{ post.text|linebreaksbr }}#}
{#      </p>#}
{#      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>#}
{#    </article>#}
{#      {% if post.group %}#}
{#        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>#}
{#      {% endif %}#}
{#      {% if not forloop.last %}<hr>{% endif %}#}
{#    <hr>#}
{#    <!-- Остальные посты. после последнего нет черты -->#}
{#    <!-- Здесь подключён паджинатор -->#}
{#    {% endfor %}#}
{#    {% include 'includes/paginator.html' %}#}
{#  </div>#}
{#{% endblock %}#}


{% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          <p>
            {{ post.text|linebreaksbr }}
          </p>
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
        {% if not forloop.last %}
          <hr>
        {% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}